<a href="https://colab.research.google.com/github/youngnamh/PyTorch/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.1+cu118


#Tensors



In [ ]:
# scalars
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

7

In [ ]:
vector = torch.tensor([7,7])
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5],
                      ],[[1,2,3,],
                        [4,5,6],
                        [7,8,9]]
                       ])
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([2, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [ ]:
TENSOR[1]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

### Random Tensors

In [ ]:
#create random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.2261, 0.0087, 0.3013, 0.0403],
        [0.2213, 0.7057, 0.9294, 0.3507],
        [0.1398, 0.4393, 0.2533, 0.4176]])

In [ ]:
#create random tensor with similar shape to an image tensor
rand_img_tensor = torch.rand(size=(224,224,3)) # can be (3,224,244) aswell can use "size="" or not
rand_img_tensor.shape, rand_img_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [ ]:
# create tensor of all zeros

In [ ]:
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones = torch.ones(2,3,4)
ones

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [ ]:
ones.dtype

torch.float32

In [ ]:
one_to_ten = torch.arange(start=1, end=1000 , step=99)
one_to_ten

tensor([  1, 100, 199, 298, 397, 496, 595, 694, 793, 892, 991])

In [ ]:
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

In [ ]:
float_32_tensor = torch.tensor([3.0,4.0,9.0],
                               dtype=None, #what datatype is the tensor,
                               device=None, #default "cpu", could be "cuda" tensors need to be on same device to work together
                               requires_grad=False) #to track gradients (still learning what this means)
float_32_tensor

tensor([3., 4., 9.])

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 4., 9.], dtype=torch.float16)

#Tensor operations : addition, subtraction, multiplication, division, matrix multiplication

In [ ]:
%%time
tensor = torch.tensor([[1,2,3],
                      [4,5,6]])
tensor + 10
tensor1 = torch.tensor([[7,8],
                        [9,10],
                        [11,12]])
torch.matmul(tensor,tensor1)

CPU times: user 144 µs, sys: 14 µs, total: 158 µs
Wall time: 165 µs


tensor([[ 58,  64],
        [139, 154]])

In [ ]:
tensor1 * 2

tensor([[14, 16],
        [18, 20],
        [22, 24]])

In [ ]:
torch.matmul(torch.rand(10,5), torch.rand(5,10)).shape

torch.Size([10, 10])

In [ ]:
torch.matmul(torch.rand(5,10), torch.rand(10,5)).shape

torch.Size([5, 5])

In [ ]:
torch.matmul(torch.rand(5,10), torch.rand(10,5))

tensor([[2.0075, 2.7510, 2.6580, 2.2679, 2.8058],
        [1.9496, 2.5208, 2.7799, 2.2943, 2.5739],
        [1.6354, 2.7421, 3.4965, 2.3136, 2.9671],
        [1.9865, 2.0310, 3.2275, 2.2831, 2.4637],
        [2.1154, 3.1020, 2.7851, 2.5326, 3.0133]])

### fix shape of matrix to meet axis for MM (transpose)

In [ ]:
t1 = torch.rand(5,10)
t2 = torch.rand(5,10)
torch.mm(t1,t2.T)

tensor([[1.6414, 2.0584, 1.7281, 2.2982, 1.5721],
        [2.4528, 1.8592, 2.2750, 2.3950, 1.7731],
        [1.8743, 1.4845, 1.1863, 1.5878, 1.1965],
        [2.3657, 1.8408, 2.5133, 2.3785, 1.7589],
        [1.9934, 1.7855, 2.3007, 1.9125, 1.5440]])

In [ ]:
(t1, t1.T)

(tensor([[0.1516, 0.9429, 0.3729, 0.2869, 0.0079, 0.9305, 0.7250, 0.9778, 0.0878,
          0.0742],
         [0.4656, 0.1057, 0.9968, 0.1953, 0.3205, 0.3122, 0.5197, 0.1829, 0.6385,
          0.9279],
         [0.3719, 0.1731, 0.7619, 0.0086, 0.8763, 0.3645, 0.4592, 0.2016, 0.2361,
          0.0690],
         [0.2008, 0.6208, 0.2890, 0.5515, 0.6058, 0.3250, 0.2894, 0.5990, 0.7958,
          0.8377],
         [0.8299, 0.5513, 0.1521, 0.6879, 0.6572, 0.4924, 0.1126, 0.4904, 0.1125,
          0.7036]]),
 tensor([[0.1516, 0.4656, 0.3719, 0.2008, 0.8299],
         [0.9429, 0.1057, 0.1731, 0.6208, 0.5513],
         [0.3729, 0.9968, 0.7619, 0.2890, 0.1521],
         [0.2869, 0.1953, 0.0086, 0.5515, 0.6879],
         [0.0079, 0.3205, 0.8763, 0.6058, 0.6572],
         [0.9305, 0.3122, 0.3645, 0.3250, 0.4924],
         [0.7250, 0.5197, 0.4592, 0.2894, 0.1126],
         [0.9778, 0.1829, 0.2016, 0.5990, 0.4904],
         [0.0878, 0.6385, 0.2361, 0.7958, 0.1125],
         [0.0742, 0.9279, 0.0690, 

In [ ]:
(t1.shape, t1.T.shape)

(torch.Size([5, 10]), torch.Size([10, 5]))

# Tensor Aggregation (mean,sum,max,min,etc)

In [ ]:
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
(x.max(), torch.max(x))

(tensor(90), tensor(90))

In [ ]:
(torch.mean(x.type(torch.float32)),x.type(torch.float32).mean())

(tensor(45.), tensor(45.))

In [ ]:
(x.sum(), torch.sum(x))

(tensor(450), tensor(450))

In [ ]:
x.argmin() #what index

tensor(0)

In [ ]:
x.argmax()

tensor(9)

In [ ]:
x[2]

tensor(20)

### Reshaping

In [ ]:
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
x_reverse = x.reshape(9,1)
x_reverse, x_reverse.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [ ]:
y = torch.arange(1., 11.)
y_re = y.reshape(2,5)
y_re

tensor([[ 1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10.]])

In [ ]:
x_stacked0 = torch.stack([x,x,x],dim=0)
x_stacked1 = torch.stack([x,x,x],dim=1)
x_stacked0, x_stacked1

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
         [1., 2., 3., 4., 5., 6., 7., 8., 9.],
         [1., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([[1., 1., 1.],
         [2., 2., 2.],
         [3., 3., 3.],
         [4., 4., 4.],
         [5., 5., 5.],
         [6., 6., 6.],
         [7., 7., 7.],
         [8., 8., 8.],
         [9., 9., 9.]]))

#Permute

In [ ]:
x_original = torch.rand(size=(224,224,3))
x_permuted = x_original.permute(2,0,1)
x_original.shape, x_permuted.shape

(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))

#Indexing

In [ ]:
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
x[0], x[0,0], x[0,2,2]

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 tensor([1, 2, 3]),
 tensor(9))

In [ ]:
x[:,2,2]

tensor([9])

In [ ]:
x[:,:,2]

tensor([[3, 6, 9]])

#Numpy

In [ ]:
import numpy as np

array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
#Tensor to Numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor,numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

#Reproduce randomness

In [ ]:
randA = torch.rand(3,4)
randB = torch.rand(3,4)

print(randA)
print(randB)
print(randA == randB)

tensor([[0.9462, 0.7328, 0.2959, 0.6650],
        [0.4898, 0.2405, 0.5455, 0.3813],
        [0.4886, 0.5114, 0.9405, 0.1956]])
tensor([[0.6833, 0.3187, 0.2525, 0.9037],
        [0.3248, 0.8195, 0.0758, 0.1024],
        [0.9148, 0.1323, 0.8798, 0.5401]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
randC = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
randD = torch.rand(3,4)

print(randC)
print(randD)
print(randC == randD )

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


#Putting tensors on the GPU

In [ ]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
tensor = torch.tensor([1,2,3])
print(tensor,tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
tensorGPU =tensor.to(device)
tensorGPU

tensor([1, 2, 3], device='cuda:0')

#move back to CPU

In [ ]:
## tensorGPU.numpy() DEVICE ERROR

TypeError: ignored

In [ ]:
tensorCPU = tensorGPU.cpu().numpy()
tensorCPU

array([1, 2, 3])